services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workboard-backend
    ports:
      - "${SERVER_PORT}:3000"
    environment:
      - DATABASE_URL="${DATABASE_URL}"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - workboard-network

  postgres:
    image: postgres:17-alpine
    container_name: workboard-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    networks:
      - workboard-network

networks:
  workboard-network:
    driver: bridge
